from fortress.exceptions import FortressException


class FortressCoreError(FortressException):
    pass
